name: Build on PR

on:
  pull_request:
    branches: ["master"]

jobs:
  build_images:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images using Docker Compose for full setup
        run: |
          docker-compose -f docker-compose.yml build

      - name: Build Docker images using Docker Compose for web & server
        run: |
          docker-compose -f build.docker-compose.yml build
